{{- if and .Values.global.secrets .Values.global.secrets.enabled}}
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace  .Release.Name ) | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
  # set below to existing secret data or generate a random one when not exists

#-- backend
{{- $baseUrlBcApi := (get $secretData "baseUrlBcApi" | b64dec | default "") }}
{{- $observationsExportUrl := (get $secretData "observationsExportUrl" | b64dec | default "") }}
{{- $observationsUrl := (get $secretData "observationsUrl" | b64dec | default "") }}
{{- $locationTypeCodeTableApi := (get $secretData "locationTypeCodeTableApi" | b64dec | default "") }}
{{- $locationNameCodeTableApi := (get $secretData "locationNameCodeTableApi" | b64dec | default "") }}
{{- $permitNumberCodeTableApi := (get $secretData "permitNumberCodeTableApi" | b64dec | default "") }}
{{- $mediaCodeTableApi := (get $secretData "mediaCodeTableApi" | b64dec | default "") }}
{{- $observedPropertiesCodeTableApi := (get $secretData "observedPropertiesCodeTableApi" | b64dec | default "") }}
{{- $projectsCodeTableApi := (get $secretData "projectsCodeTableApi" | b64dec | default "") }}
{{- $apiKey := (get $secretData "apiKey" | b64dec | default "") }}
{{- $authToken := (get $secretData "authToken" | b64dec | default "") }}

#-- frontend
{{- $apiName := (get $secretData "apiName" | b64dec | default "") }}
{{- $baseUrl := (get $secretData "baseUrl" | b64dec | default "") }}
{{- $reactAppApiUrl := .Values.global.secrets.reactAppApiUrl| default "/api" }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend
  labels: {{- include "labels" . | nindent 4 }}
  {{- if .Values.global.secrets.persist }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  BASE_URL_BC_API:  {{ $baseUrlBcApi | b64enc | quote }}
  OBSERVATIONS_EXPORT_URL:  {{ $observationsExportUrl | b64enc | quote }}
  OBSERVATIONS_URL:  {{ $observationsUrl | b64enc | quote }}
  LOCATION_TYPE_CODE_TABLE_API:  {{ $locationTypeCodeTableApi | b64enc | quote }}
  LOCATION_NAME_CODE_TABLE_API:  {{ $locationNameCodeTableApi | b64enc | quote }}
  PERMIT_NUMBER_CODE_TABLE_API:  {{ $permitNumberCodeTableApi | b64enc | quote }}
  MEDIA_CODE_TABLE_API:  {{ $mediaCodeTableApi | b64enc | quote }}
  OBSERVED_PROPERTIES_CODE_TABLE_API:  {{ $observedPropertiesCodeTableApi | b64enc | quote }}
  PROJECTS_CODE_TABLE_API:  {{ $projectsCodeTableApi | b64enc | quote }}
  API_KEY:  {{ $apiKey | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-frontend
  labels: {{- include "labels" . | nindent 4 }}
  {{- if .Values.global.secrets.persist }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
data:
  # FRONTEND Secrets
  PORT:  "3000"

{{- end }}










